from __future__ import annotations

import logging
import math
import queue
import random
import re
import threading
import time
import uuid
from collections.abc import AsyncIterator, Iterator
from contextlib import asynccontextmanager
from functools import partial
from typing import Annotated, Any

from fastapi import Depends, FastAPI, Header, HTTPException, Path, Query, Request, Response
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse, StreamingResponse
from pydantic import BaseModel, Field
from starlette.exceptions import HTTPException as StarletteHTTPException

from eurostream import __version__
from eurostream.alerts import AlertBroker, format_event, parse_last_event_id
from eurostream.config import Settings
from eurostream.dashboard import get_dashboard_html
from eurostream.governance.audit_chain import verify_audit_log
from eurostream.governance.erasure import ErasureAudit, ErasureService
from eurostream.governance.pii import PIIClassifier
from eurostream.idempotency import (
    IDEMPOTENCY_KEY_PATTERN,
    IdempotencyConflictError,
    IdempotencyStore,
)
from eurostream.lineage import LineageEmitter
from eurostream.logging import configure_logging, reset_request_id, set_request_id
from eurostream.metrics import Metrics
from eurostream.models import ErasureRequested
from eurostream.orchestration import DAG, DAGTask
from eurostream.producers import ClickProducer, OrderProducer, PaymentProducer
from eurostream.quality import DataQualityEngine
from eurostream.ratelimit import RateLimiter
from eurostream.resilience import RetryPolicy, call_with_retry
from eurostream.streaming import FraudAlert, FraudScorer, FraudStreamProcessor
from eurostream.warehouse import Warehouse

logger = logging.getLogger(__name__)

PROBLEM_MEDIA_TYPE = "application/problem+json"
REQUEST_ID_HEADER = "X-Request-ID"
# Customer identifiers are generated by the producers (`cust_<digits>`), so a
# tight charset is enough — and it means no path param can reach SQL as syntax.
CUSTOMER_ID_PATTERN = re.compile(r"^[A-Za-z0-9_.\-]{1,64}$")

CustomerId = Annotated[
    str,
    Path(
        pattern=CUSTOMER_ID_PATTERN.pattern,
        description="Customer identifier (letters, digits, `_`, `.`, `-`; max 64 chars)",
    ),
]


def problem(
    status: int,
    title: str,
    detail: str,
    *,
    type_uri: str = "about:blank",
    headers: dict[str, str] | None = None,
) -> JSONResponse:
    """RFC 9457 problem+json — one error shape for every failure the API returns."""
    body: dict[str, object] = {
        "type": type_uri,
        "title": title,
        "status": status,
        "detail": detail,
    }
    return JSONResponse(
        status_code=status,
        content=body,
        media_type=PROBLEM_MEDIA_TYPE,
        headers=headers,
    )


def service_unavailable(detail: str) -> JSONResponse:
    """A dependency (bus/warehouse) is not wired up, so the route cannot run."""
    return problem(
        503,
        "Service unavailable",
        detail,
        type_uri="https://eurostream.dev/problems/service-unavailable",
    )


_STATUS_TITLES = {
    400: "Bad request",
    401: "Unauthorized",
    403: "Forbidden",
    404: "Not found",
    405: "Method not allowed",
    409: "Conflict",
    413: "Payload too large",
    415: "Unsupported media type",
    422: "Validation error",
    429: "Too many requests",
    500: "Internal server error",
    501: "Not implemented",
    503: "Service unavailable",
    504: "Gateway timeout",
}


def _status_title(status: int) -> str:
    return _STATUS_TITLES.get(status, "Error")


class _LakeFallback:
    """Row counts from the public Hugging Face Parquet lake, cached.

    The dashboard polls ``/stats`` every few seconds and a cold ``hf://``
    read costs seconds per table, so an uncached fallback would make a fresh
    deployment feel permanently hung. Negative results are cached too.
    """

    _TTL_SECONDS = 300.0

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._repo: str | None = None
        self._at = 0.0
        self._stats: dict[str, int] = {}
        self._populated = False

    def get(self, repo: str) -> dict[str, int]:
        with self._lock:
            if (
                self._populated
                and self._repo == repo
                and time.time() - self._at < self._TTL_SECONDS
            ):
                return dict(self._stats)
        stats = self._fetch(repo)
        with self._lock:
            self._repo = repo
            self._at = time.time()
            self._stats = stats
            self._populated = True
        return dict(stats)

    @staticmethod
    def _fetch(repo: str) -> dict[str, int]:
        tables = (
            ("silver/orders", "silver_customers"),
            ("gold/customer_360", "gold_customers"),
            ("gold/order_facts", "gold_order_facts"),
            ("gold/fraud_summary", "fraud_alerts"),
        )
        out: dict[str, int] = {}
        cleaned = repo.strip().strip("\"' \t\r\n")
        if not cleaned or not all(c.isalnum() or c in "-_./" for c in cleaned):
            logger.warning("refusing lake fallback for unsafe repo id %r", repo)
            return out
        try:
            import duckdb

            hf_base = f"hf://datasets/{cleaned}"
            # A remote parquet read over hf:// fails transiently (cold cache,
            # hub hiccup); one jittered second attempt costs less than
            # reporting an empty lake. Anything else is a real miss.
            lake_retry = RetryPolicy(attempts=2, base_delay=0.15)

            def read_count(tbl: str) -> int:
                row = duckdb.query(
                    f"SELECT count(*) FROM read_parquet('{hf_base}/{tbl}.parquet')"  # noqa: S608
                ).fetchone()
                return int(row[0]) if row and row[0] else 0

            for tbl, key in tables:
                try:
                    count = call_with_retry(partial(read_count, tbl), policy=lake_retry)
                    if count:
                        out[key] = count
                except Exception as e:
                    logger.debug("lake fallback %s failed: %s", tbl, e)
        except Exception as e:
            logger.warning("HF lake fallback unavailable: %s", e)
        return out


_LAKE_FALLBACK = _LakeFallback()


class ErasureRequest(BaseModel):
    customer_id: str = Field(
        min_length=3,
        max_length=64,
        pattern=CUSTOMER_ID_PATTERN.pattern,
        description="Customer identifier (letters, digits, `_`, `.`, `-`)",
    )
    reason: str = Field(default="GDPR_ARTICLE_17", max_length=64)
    sync: bool = Field(
        default=False,
        description="Run the deletion cascade inline instead of enqueueing it.",
    )


#: Identifier length bound for a request id path parameter.
REQUEST_ID_MAX = 128

ErasureRequestId = Annotated[
    str,
    Path(
        pattern=rf"^[A-Za-z0-9_.\-]{{1,{REQUEST_ID_MAX}}}$",
        description="Erasure request id (as returned in `request_id`)",
    ),
]

#: Every status an erasure request can be in, from intake to verdict.
ERASURE_STATUSES = ("queued", "executing", "completed", "failed", "completed_with_errors")


def _pending_item(entry: dict[str, object]) -> dict[str, object]:
    """Shape an intake entry like an audit row, with the absent fields null."""
    requested_at = entry.get("requested_at")
    return {
        "request_id": entry.get("request_id"),
        "customer_id": entry.get("customer_id"),
        "status": entry.get("status"),
        "requested_at": requested_at if isinstance(requested_at, (int, float)) else None,
        "completed_at": None,
        "duration_seconds": None,
        "layers_touched": [],
        "confirmation_hash": None,
        "requested_by": entry.get("requested_by"),
    }


def _audit_item(row: dict[str, object]) -> dict[str, object]:
    """Shape an audit-log row for the API (duration derived, layers split)."""
    requested_at = row.get("requested_at")
    completed_at = row.get("completed_at")
    requested = float(requested_at) if isinstance(requested_at, (int, float)) else None
    completed = float(completed_at) if isinstance(completed_at, (int, float)) else None
    layers = [layer for layer in str(row.get("layers_touched") or "").split(",") if layer]
    duration = (
        round(completed - requested, 3) if requested is not None and completed is not None else None
    )
    return {
        "request_id": row.get("request_id"),
        "customer_id": row.get("customer_id"),
        "status": row.get("status"),
        "requested_at": requested,
        "completed_at": completed,
        "duration_seconds": duration,
        "layers_touched": layers,
        "confirmation_hash": row.get("confirmation_hash"),
        "requested_by": None,
    }


def _requested_ts(item: dict[str, object]) -> float:
    """Sort key for request timestamps; missing/odd values sort oldest."""
    value = item.get("requested_at")
    return float(value) if isinstance(value, (int, float)) else 0.0


def _bus_backend(bus: Any) -> str:
    """Report the backend actually in use, not the one that was requested."""
    if bus is None:
        return "none"
    return "kafka" if type(bus).__module__.endswith(".bus.kafka") else "sqlite"


def create_app(
    erasure: ErasureService,
    metrics: Metrics,
    settings: Settings,
    warehouse: Warehouse | None = None,
    bus: Any = None,
    *,
    backend: str | None = None,
    start_worker: bool = True,
    api_token: str | None = None,
) -> FastAPI:
    """Build the FastAPI app.

    ``backend`` overrides the detected event-bus backend (used when the bus
    proxy hides its concrete type). ``start_worker`` runs the erasure consumer
    as a lifespan thread so queued Art. 17 requests actually execute — without
    it the ``/erasure-requests`` endpoint would only pretend to enqueue.
    ``api_token`` locks down the mutating routes when set (via
    ``EUROSTREAM_API_TOKEN``).
    """
    effective_backend = backend or _bus_backend(bus)
    requested_backend = settings.event_bus_backend
    # Live alert fan-out for GET /stream/alerts (see eurostream.alerts).
    broker = AlertBroker()

    def publish_alert(alert: FraudAlert) -> None:
        broker.publish(alert.to_dict())

    # One processor, one consumer group, one owner. Two consumers in a group
    # would each score every payment and land duplicate alerts; the lock makes
    # the background loop and POST /stream take turns on the same consumer.
    fraud_processor: FraudStreamProcessor | None = None
    if bus is not None and warehouse is not None:
        fraud_processor = FraudStreamProcessor(
            consumer=bus.consumer(
                "payments", settings.fraud_consumer_group, auto_offset_reset="earliest"
            ),
            scorer=FraudScorer(settings, metrics),
            metrics=metrics,
            output_producer=bus,
            alert_topic="fraud_alerts",
            suppression_check=erasure.is_suppressed,
            on_alert=publish_alert,
        )
    fraud_lock = threading.Lock()
    # Filled in by the lifespan; /stats reports liveness from the threads
    # themselves rather than from what the configuration says should happen.
    workers: dict[str, threading.Thread | None] = {"erasure": None, "fraud": None}
    # Retry safety for the one endpoint that deletes data (see idempotency.py).
    idempotency = IdempotencyStore()
    # Per-client pacing for the routes that change state (see ratelimit.py).
    limiter = RateLimiter(settings.api_rate_limit, settings.api_rate_limit_burst)
    # Format every EuroStream line the way this deployment wants it before the
    # first log fires (lifespan, worker, request handlers).
    configure_logging(settings.log_level, settings.log_format)
    degraded = effective_backend != requested_backend
    if degraded:
        logger.warning(
            "event bus degraded: requested=%s effective=%s",
            requested_backend,
            effective_backend,
        )

    @asynccontextmanager
    async def lifespan(_: FastAPI) -> AsyncIterator[None]:
        stop = threading.Event()
        worker: threading.Thread | None = None
        fraud_worker: threading.Thread | None = None

        def fraud_loop() -> None:
            """Drain the payments topic until shutdown.

            `run()` returns after a short idle stretch, which is the loop's
            natural tick: ingest what arrived, then wait to be woken. Alerts
            are ingested while the fraud lock is held so a `POST /stream`
            cannot interleave two alert sets into bronze.
            """
            assert fraud_processor is not None and warehouse is not None
            while not stop.is_set():
                with fraud_lock:
                    alerts = fraud_processor.run(poll_timeout=0.2, idle_stop=5)
                    if alerts:
                        warehouse.ingest_fraud_alerts([a.to_dict() for a in alerts])
                if alerts:
                    metrics.flush()
                stop.wait(0.5)

        if start_worker and bus is not None:
            worker = threading.Thread(
                target=erasure.run_worker,
                kwargs={"poll_timeout": 0.2, "stop_event": stop},
                name="eurostream-erasure-worker",
                daemon=True,
            )
            worker.start()
            workers["erasure"] = worker
            logger.info("erasure worker running in background")
        if (
            start_worker
            and settings.fraud_worker_enabled
            and fraud_processor is not None
            and warehouse is not None
        ):
            fraud_worker = threading.Thread(
                target=fraud_loop,
                name="eurostream-fraud-worker",
                daemon=True,
            )
            fraud_worker.start()
            workers["fraud"] = fraud_worker
            logger.info(
                "fraud scoring worker running in background (group=%s)",
                settings.fraud_consumer_group,
            )
        try:
            yield
        finally:
            stop.set()
            if fraud_processor is not None:
                # Unblocks a poll mid-drain; the processor is not reused.
                fraud_processor.stop()
            if worker is not None:
                worker.join(timeout=5)
            if fraud_worker is not None:
                fraud_worker.join(timeout=5)
            metrics.flush()
            logger.info("shutdown complete: metrics flushed")

    app = FastAPI(
        title="EuroStream Governance API",
        version=__version__,
        description=(
            "GDPR-compliant real-time customer analytics, DSAR right-to-erasure "
            "cascade, and Prometheus observability."
        ),
        lifespan=lifespan,
        contact={"name": "EuroStream", "url": "https://github.com/swadhinbiswas/eurostream"},
        license_info={"name": "MIT"},
        servers=[{"url": "/", "description": "This server"}],
    )
    # Exposed for the dashboard/tests: publish an alert and watch it leave
    # through GET /stream/alerts.
    app.state.alert_broker = broker

    origins = [o.strip() for o in settings.cors_origins.split(",") if o.strip()]
    wildcard = "*" in origins
    app.add_middleware(
        CORSMiddleware,
        allow_origins=origins,
        # Credentialed CORS is only safe with an explicit origin allowlist.
        allow_credentials=not wildcard,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Content-Type", "X-Request-ID", "Idempotency-Key"]
        + (["Authorization"] if api_token else []),
        expose_headers=[REQUEST_ID_HEADER, "Idempotent-Replay"],
    )

    @app.middleware("http")
    async def request_id_middleware(request: Request, call_next: Any) -> Any:
        rid = request.headers.get(REQUEST_ID_HEADER) or uuid.uuid4().hex
        request.state.request_id = rid
        # Bind the correlation id for everything logged while this request is
        # in scope — including the sync endpoints running on worker threads.
        token = set_request_id(rid)
        try:
            started = time.perf_counter()
            response = await call_next(request)
            elapsed = time.perf_counter() - started
        finally:
            reset_request_id(token)
        response.headers[REQUEST_ID_HEADER] = rid

        # Label by the *route template* (from the matched route, not the raw
        # URL) so an attacker cannot blow up the metrics cardinality with
        # arbitrary path segments.
        route = request.scope.get("route")
        path_label = getattr(route, "path", None) or "/"
        metrics.observe("http_request_duration_seconds", elapsed)
        metrics.record_request(response.status_code)
        metrics.incr(
            "http_requests_total",
            labels={
                "method": request.method,
                "path": path_label,
                "status": str(response.status_code),
            },
        )
        # Structured access line: the request id in this record matches the
        # response header and every log line emitted while handling it. It is
        # passed explicitly because this line runs after the scope is reset.
        logger.info(
            "%s %s -> %s",
            request.method,
            path_label,
            response.status_code,
            extra={
                "request_id": rid,
                "method": request.method,
                "path": path_label,
                "status": response.status_code,
                "duration_ms": round(elapsed * 1000, 3),
            },
        )
        return response

    @app.exception_handler(StarletteHTTPException)
    async def http_exception_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
        detail = exc.detail if isinstance(exc.detail, str) else str(exc.detail)
        return problem(
            exc.status_code,
            _status_title(exc.status_code),
            detail,
            headers=dict(getattr(exc, "headers", None) or {}),
        )

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(
        request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        problems = []
        for err in exc.errors():
            loc = ".".join(str(p) for p in err.get("loc", ()) if p != "body")
            problems.append(f"{loc}: {err.get('msg', 'invalid')}")
        return problem(
            422,
            "Validation error",
            "; ".join(problems) or "request body failed validation",
        )

    @app.exception_handler(Exception)
    async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
        rid = getattr(request.state, "request_id", "-")
        logger.exception("unhandled error [%s] on %s %s", rid, request.method, request.url.path)
        return problem(
            500,
            "Internal server error",
            f"unexpected failure (request id {rid})",
        )

    def rate_limit(request: Request) -> None:
        """Per-client token bucket on mutating routes; 429 problem+json.

        The key is the first hop of X-Forwarded-For when present (the
        platform runs behind a proxy in every deployment that matters) and
        the socket address otherwise.
        """
        if not limiter.enabled:
            return
        client = request.client.host if request.client else "unknown"
        forwarded = request.headers.get("X-Forwarded-For", "")
        if forwarded:
            client = forwarded.split(",")[0].strip() or client
        allowed, retry_after = limiter.check(client)
        if not allowed:
            metrics.incr("rate_limited_requests")
            retry = max(1, int(math.ceil(retry_after)))
            raise HTTPException(
                status_code=429,
                detail=f"rate limit exceeded for {client}; retry in {retry}s",
                headers={"Retry-After": str(retry)},
            )

    def require_token(request: Request) -> None:
        if not api_token:
            return
        supplied = request.headers.get("Authorization", "").removeprefix("Bearer ").strip()
        if supplied != api_token:
            raise HTTPException(
                status_code=401,
                detail="missing or invalid bearer token",
                headers={"WWW-Authenticate": "Bearer"},
            )

    @app.get("/", response_class=HTMLResponse, include_in_schema=False)
    def root_dashboard() -> str:
        return get_dashboard_html()

    @app.get("/dashboard", response_class=HTMLResponse, include_in_schema=False)
    def dashboard_view() -> str:
        return get_dashboard_html()

    @app.get("/api", tags=["meta"], summary="Endpoint index")
    def api_index() -> dict[str, object]:
        return {
            "name": "EuroStream Governance API",
            "version": __version__,
            "docs": "/docs",
            "health": "/health",
            "health_live": "/health/live",
            "health_ready": "/health/ready",
            "stats": "/stats",
            "metrics": "/metrics",
            "prometheus": "/metrics/prometheus",
            "erasure_audit": "/governance/erasure-audit",
            "erasure_audit_verify": "/governance/erasure-audit/verify",
            "customer_360": "/gold/customer-360",
            "fraud_summary": "/gold/fraud_summary",
            "fraud_alerts": "/fraud_alerts",
            "alerts_sse": "/stream/alerts",
            "data_quality_runs": "/governance/data_quality_runs",
            "suppression_registry": "/governance/suppression-registry",
            "watermarks": "/governance/watermarks",
            "erasure_verify": "/verify-erasure/{customer_id}",
            "erasure_requests": "/erasure-requests",
            "erasure_request_status": "/erasure-requests/{request_id}",
            "turso_status": "/turso/status",
        }

    @app.get("/stats", tags=["analytics"], summary="Pipeline row counts and runtime settings")
    def pipeline_stats() -> dict[str, object]:
        stats: dict[str, object] = {
            "version": __version__,
            "backend": effective_backend,
            "requested_backend": requested_backend,
            "degraded": degraded,
            "sla_seconds": settings.erasure_sla_seconds,
            "fraud_window_seconds": settings.fraud_window_seconds,
            "fraud_velocity_threshold": settings.fraud_velocity_threshold,
            "suppressed_customers": len(erasure.suppressed_customers()),
            "turso_connected": warehouse.turso is not None if warehouse else False,
            "source": "duckdb" if warehouse is not None else "none",
            # Rolling SLO: the dashboard's error-budget panel reads this.
            "slo": metrics.slo(),
            "rate_limit": {
                "rate_per_second": settings.api_rate_limit,
                "burst": settings.api_rate_limit_burst,
                "enabled": limiter.enabled,
                "rejected": limiter.rejected,
            },
            "alerts": broker.stats(),
            "fraud_worker": {
                "enabled": settings.fraud_worker_enabled,
                "running": bool(workers["fraud"] and workers["fraud"].is_alive()),
                "group": settings.fraud_consumer_group,
                "processor": fraud_processor is not None,
            },
            "erasure_worker": {
                "running": bool(workers["erasure"] and workers["erasure"].is_alive()),
            },
        }
        if warehouse is not None:
            try:
                stats["bronze_orders"] = warehouse.scalar("SELECT count(*) FROM bronze.orders")
                stats["bronze_clicks"] = warehouse.scalar("SELECT count(*) FROM bronze.clicks")
                stats["bronze_payments"] = warehouse.scalar("SELECT count(*) FROM bronze.payments")
                stats["bronze_fraud_alerts"] = warehouse.scalar(
                    "SELECT count(*) FROM bronze.fraud_alerts"
                )
                stats["silver_customers"] = warehouse.scalar(
                    "SELECT count(*) FROM silver.customers"
                )
                stats["silver_orders"] = warehouse.scalar("SELECT count(*) FROM silver.orders")
                stats["silver_payments"] = warehouse.scalar("SELECT count(*) FROM silver.payments")
                stats["gold_customers"] = warehouse.scalar("SELECT count(*) FROM gold.customer_360")
                stats["gold_order_facts"] = warehouse.scalar(
                    "SELECT count(*) FROM gold.order_facts"
                )
                stats["fraud_alerts"] = warehouse.scalar("SELECT count(*) FROM gold.fraud_summary")
                try:
                    stats["silver_watermark"] = warehouse.get_watermark("silver")
                    stats["gold_watermark"] = warehouse.get_watermark("gold")
                    lp = settings.data_dir / "lineage.jsonl"
                    if lp.exists():
                        lines = lp.read_text().strip().splitlines()
                        if lines:
                            stats["lineage"] = lines[-1][:400]
                except Exception as e:  # noqa: S110
                    logger.debug("watermark/lineage read failed: %s", e)
            except Exception as e:
                # Never report a partial picture as a healthy one.
                logger.warning("Failed to query stats from warehouse: %s", e)
                stats["errors"] = [f"warehouse query failed: {e}"]

        stats["total_rows"] = sum(
            int(str(stats.get(k, 0) or 0))
            for k in [
                "bronze_orders",
                "bronze_clicks",
                "bronze_payments",
                "silver_customers",
                "gold_customers",
            ]
        )
        try:
            lake_root = settings.lake_root
            stats["lake_files"] = (
                sum(1 for p in lake_root.rglob("*.parquet") if p.is_file())
                if lake_root.exists()
                else 0
            )
        except Exception as e:  # noqa: BLE001 - a missing lake is not a stats failure
            logger.debug("lake file count failed: %s", e)
            stats["lake_files"] = 0

        # Cloud fallback: query Hugging Face Lake if local storage is
        # completely empty. Cached, because the dashboard polls /stats every
        # few seconds and a cold `hf://` read costs seconds per table.
        if stats["total_rows"] == 0:
            cached = _LAKE_FALLBACK.get(settings.hf_repo)
            if cached:
                stats.update(cached)
                stats["total_rows"] = sum(
                    int(str(stats.get(k, 0) or 0))
                    for k in [
                        "bronze_orders",
                        "bronze_clicks",
                        "bronze_payments",
                        "silver_customers",
                        "gold_customers",
                    ]
                )
                if stats["total_rows"] > 0:
                    stats["source"] = "hf_lake"
        return stats

    @app.post(
        "/erasure-requests",
        tags=["governance"],
        summary="Accept a GDPR Art. 17 right-to-erasure request",
        status_code=202,
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={
            202: {"description": "Request accepted and queued for execution"},
            200: {"description": "Cascade executed synchronously (sync=true)"},
            401: {"description": "Missing or invalid bearer token"},
            409: {"description": "Idempotency-Key reused for another customer, or still in flight"},
            422: {"description": "Invalid customer identifier or Idempotency-Key"},
        },
    )
    def request_erasure(
        body: ErasureRequest,
        response: Response,
        idempotency_key: Annotated[
            str | None,
            Header(
                alias="Idempotency-Key",
                pattern=IDEMPOTENCY_KEY_PATTERN,
                description=(
                    "Retry-safe key. Replaying the same key with the same "
                    "customer returns the first response unchanged "
                    "(with `Idempotent-Replay: true`); reusing it for another "
                    "customer is a 409."
                ),
            ),
        ] = None,
    ) -> Any:
        """Accepts a GDPR Art. 17 right-to-erasure request. Enqueues a tombstone
        on the bus for the background worker; with ``sync=true`` the full
        deletion cascade runs inline and the response carries its proof.

        Send ``Idempotency-Key`` when retrying: a duplicate POST replays the
        original answer instead of opening a second DSAR.
        """
        key = idempotency_key
        if key is not None:
            try:
                replay = idempotency.begin(key, body.customer_id)
            except IdempotencyConflictError as exc:
                metrics.incr("idempotency_conflicts")
                raise HTTPException(status_code=409, detail=str(exc)) from exc
            if replay is not None:
                metrics.incr("idempotent_replays")
                return JSONResponse(
                    status_code=replay.status_code,
                    content=replay.body,
                    headers={"Idempotent-Replay": "true"},
                )

        status_code = 202
        try:
            request_id = erasure.request_erasure(
                body.customer_id,
                requested_by="dsar@eurocart.eu",
            )
            if body.sync:
                event = ErasureRequested(
                    event_id=request_id,
                    occurred_at=time.time(),
                    request_id=request_id,
                    customer_id=body.customer_id,
                )
                audit = erasure.execute(event)
                payload: dict[str, object] = {
                    "request_id": request_id,
                    "customer_id": body.customer_id,
                    "status": audit.status,
                    "confirmation_hash": audit.confirmation_hash,
                    "layers_touched": audit.layers_touched,
                    "sla_seconds": settings.erasure_sla_seconds,
                    "latency_seconds": round(audit.completed_at - audit.requested_at, 3),
                }
                # Executed inline, so this is a completed resource.
                status_code = 200
            else:
                payload = {
                    "request_id": request_id,
                    "customer_id": body.customer_id,
                    "status": "queued",
                    "sla_seconds": settings.erasure_sla_seconds,
                }
        except Exception:
            # A failed attempt must not keep the key claimed, or the client's
            # retry would 409 against its own half-finished request.
            if key is not None:
                idempotency.fail(key)
            raise

        if key is not None:
            idempotency.complete(
                key,
                customer_id=body.customer_id,
                request_id=str(payload.get("request_id") or ""),
                status_code=status_code,
                body=payload,
            )
        if status_code == 200:
            return JSONResponse(status_code=200, content=payload)
        return payload

    @app.get(
        "/erasure-requests",
        tags=["governance"],
        summary="List erasure requests, queued and executed",
        responses={
            422: {"description": "Invalid status, customer id or paging values"},
            503: {"description": "Warehouse is not configured"},
        },
    )
    def list_erasure_requests(
        status: str | None = Query(
            default=None,
            pattern="^(" + "|".join(ERASURE_STATUSES) + ")$",
            description="Only return requests in this state",
        ),
        customer_id: str | None = Query(
            default=None,
            pattern=CUSTOMER_ID_PATTERN.pattern,
            description="Only return requests for this customer",
        ),
        limit: int = Query(default=50, ge=1, le=200, description="Page size"),
        offset: int = Query(default=0, ge=0, description="Rows to skip"),
    ) -> dict[str, object]:
        """Merges the intake queue (accepted, not yet executed) with the
        durable audit log, newest first. Reads are pinned to the local
        warehouse so a compliance list never answers from a stale replica."""
        items = [_pending_item(entry) for entry in erasure.pending_requests()]
        wh = require_warehouse()
        items.extend(
            _audit_item(row)
            for row in wh.query(
                "SELECT request_id, customer_id, requested_at, completed_at, "
                "layers_touched, status, confirmation_hash "
                "FROM governance.erasure_audit_log",
                local_only=True,
            )
        )
        if status is not None:
            items = [item for item in items if item["status"] == status]
        if customer_id is not None:
            items = [item for item in items if item["customer_id"] == customer_id]
        items.sort(key=_requested_ts, reverse=True)
        return {
            "total": len(items),
            "limit": limit,
            "offset": offset,
            "items": items[offset : offset + limit],
        }

    @app.get(
        "/erasure-requests/{request_id}",
        tags=["governance"],
        summary="Status of one erasure request",
        responses={
            404: {"description": "No such request id"},
            422: {"description": "Invalid request id"},
            503: {"description": "Warehouse is not configured and the id is not queued"},
        },
    )
    def erasure_request_status(request_id: ErasureRequestId) -> dict[str, object]:
        """Answers with the intake entry while the request is queued or
        executing and with the audit row once the cascade finished — one URL
        for the whole 202-to-verdict lifecycle."""
        pending = erasure.pending_request(request_id)
        if pending is not None:
            return _pending_item(pending)
        wh = require_warehouse()
        rows = wh.query(
            "SELECT request_id, customer_id, requested_at, completed_at, "
            "layers_touched, status, confirmation_hash "
            "FROM governance.erasure_audit_log WHERE request_id = ?",
            (request_id,),
            local_only=True,
        )
        if not rows:
            raise HTTPException(status_code=404, detail=f"no erasure request with id {request_id}")
        return _audit_item(rows[0])

    @app.post(
        "/erase/{customer_id}",
        tags=["governance"],
        summary="Execute the deletion cascade synchronously",
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={
            401: {"description": "Missing or invalid bearer token"},
            422: {"description": "Invalid customer identifier"},
            500: {"description": "Cascade failed; recorded as status=failed in the audit log"},
        },
    )
    def erase_customer_sync(customer_id: CustomerId) -> dict[str, object]:
        """Directly executes the layered right-to-erasure cascade for a customer ID.

        Irreversible: Bronze PII is overwritten in place. Returns 500 with a
        problem+json body if any layer fails, and the attempt is audited.
        """
        request_id = erasure.request_erasure(customer_id, requested_by="dsar@eurocart.eu")
        event = ErasureRequested(
            event_id=request_id,
            occurred_at=time.time(),
            request_id=request_id,
            customer_id=customer_id,
        )
        audit = erasure.execute(event)
        metrics.flush()
        return {
            "request_id": request_id,
            "customer_id": customer_id,
            "status": audit.status,
            "confirmation_hash": audit.confirmation_hash,
            "layers_touched": audit.layers_touched,
            "sla_seconds": settings.erasure_sla_seconds,
            "latency_seconds": round(audit.completed_at - audit.requested_at, 3),
        }

    @app.get(
        "/verify-erasure/{customer_id}",
        tags=["governance"],
        summary="Verify proof of deletion for a customer",
        responses={422: {"description": "Invalid customer identifier"}},
    )
    def verify_erasure(customer_id: CustomerId) -> dict[str, object]:
        """Verifies proof of deletion across every warehouse layer.

        All values are bound as query parameters and the reads are pinned to
        the local warehouse (`local_only`) so a cloud replica can never be the
        source of a compliance verdict.
        """
        is_suppressed = erasure.is_suppressed(customer_id)
        gold_remaining = 0
        silver_remaining = 0
        bronze_clear = 0
        bronze_anon = 0
        audit_count = 0
        if warehouse is not None:
            gold_remaining = warehouse.scalar(
                "SELECT count(*) FROM gold.customer_360 WHERE customer_id=?",
                (customer_id,),
                local_only=True,
            )
            silver_remaining = warehouse.scalar(
                "SELECT count(*) FROM silver.customers WHERE customer_id=?",
                (customer_id,),
                local_only=True,
            )
            bronze_clear = warehouse.scalar(
                "SELECT count(*) FROM bronze.orders "
                "WHERE customer_id=? AND email <> '<anonymized>'",
                (customer_id,),
                local_only=True,
            )
            bronze_anon = warehouse.scalar(
                "SELECT count(*) FROM bronze.orders WHERE customer_id=? AND email = '<anonymized>'",
                (customer_id,),
                local_only=True,
            )
            audit_count = warehouse.scalar(
                "SELECT count(*) FROM governance.erasure_audit_log WHERE customer_id=?",
                (customer_id,),
                local_only=True,
            )

        verified = (
            is_suppressed
            and gold_remaining == 0
            and silver_remaining == 0
            and bronze_clear == 0
            and audit_count >= 1
        )
        return {
            "customer_id": customer_id,
            "verified": verified,
            "is_suppressed": is_suppressed,
            "gold_rows_remaining": gold_remaining,
            "silver_rows_remaining": silver_remaining,
            "bronze_clear_text_rows": bronze_clear,
            "bronze_anonymized_rows": bronze_anon,
            "audit_log_entries": audit_count,
        }

    @app.post(
        "/produce",
        tags=["pipeline"],
        summary="Emit synthetic EU events to the bus",
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={
            503: {"description": "No event bus is wired into this server"},
        },
    )
    def trigger_produce(
        events: int = Query(
            default=100, ge=1, le=5000, description="Orders to emit (3 events each)"
        ),
        burst_customer: str | None = Query(
            default=None, description="Force a velocity burst for this customer"
        ),
    ) -> Any:
        """Emits synthetic EU events to the bus topics."""
        if bus is None:
            return service_unavailable("no event bus is wired into this server")
        order = OrderProducer(bus, settings)
        click = ClickProducer(bus, settings)
        payment = PaymentProducer(bus, settings)
        for i in range(events):
            order.emit()
            click.emit()
            payment.emit()
            if burst_customer and (i % 3 == 0):
                payment.emit(
                    customer_id=burst_customer,
                    amount=random.uniform(900, 2000),
                    country="DE",
                    merchant_country="NL",
                )
        # Emit a couple of natural anomalies to ensure fraud scorer has alerts to catch
        anom_cust = burst_customer or f"cust_burst_{random.randint(100, 999)}"
        for _ in range(settings.fraud_velocity_threshold + 2):
            payment.emit(
                customer_id=anom_cust,
                amount=random.uniform(700, 1500),
                country="DE",
                merchant_country="FR",
            )
        if hasattr(bus, "flush"):
            bus.flush()
        metrics.incr("events_produced", events * 3)
        metrics.flush()
        return {
            "status": "ok",
            "events_produced": events,
            "topics": ["orders", "clicks", "payments"],
            "anom_target": anom_cust,
        }

    @app.post(
        "/stream",
        tags=["pipeline"],
        summary="Score pending payments for fraud",
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={503: {"description": "Bus or warehouse is not wired into this server"}},
    )
    def trigger_stream(
        max_events: int = Query(default=200, ge=1, le=5000, description="Payments to consume"),
    ) -> Any:
        """Consumes payments and runs real-time FraudScorer."""
        if bus is None or warehouse is None:
            return service_unavailable("event bus or warehouse is not wired into this server")
        if fraud_processor is None:
            return service_unavailable("event bus or warehouse is not wired into this server")
        with fraud_lock:
            alerts = fraud_processor.run(max_events=max_events)
            warehouse.ingest_fraud_alerts([a.to_dict() for a in alerts])
        metrics.flush()
        return {
            "status": "ok",
            "alerts_emitted": len(alerts),
            "alerts": [a.to_dict() for a in alerts[:20]],
        }

    @app.get(
        "/stream/alerts",
        tags=["pipeline"],
        summary="Live fraud alerts as Server-Sent Events",
        response_class=StreamingResponse,
        responses={
            200: {
                "description": (
                    "`text/event-stream` of fraud alerts as they are scored. "
                    "Each frame carries `id` (the resume point), `event: alert` "
                    "and a JSON `data` payload. A `: ping` comment is emitted "
                    "every `heartbeat` seconds so proxies keep the connection open."
                ),
                "content": {"text/event-stream": {}},
            },
        },
    )
    def stream_alerts(
        since: int | None = Query(
            default=None,
            ge=0,
            description=(
                "Replay buffered alerts after this event id. Defaults to the "
                "standard `Last-Event-ID` header (browsers send it on reconnect); "
                "with neither, the stream starts live."
            ),
        ),
        last_event_id: Annotated[
            str | None,
            Header(alias="Last-Event-ID", description="Event id of the last frame this client saw"),
        ] = None,
        heartbeat: float = Query(
            default=15.0, ge=0.1, le=60.0, description="Seconds between `: ping` comments"
        ),
        duration: float | None = Query(
            default=None,
            ge=0.0,
            le=3600.0,
            description="Close the stream after this many seconds (omit to stream until disconnect)",
        ),
    ) -> StreamingResponse:
        """Server-Sent Events feed of fraud alerts scored by `POST /stream`.

        Reconnecting clients resume without a gap: send `Last-Event-ID` (or
        `?since=`) and the buffered events after it are replayed before the
        live tail.
        """
        resume = since if since is not None else parse_last_event_id(last_event_id)
        # Only a client that states a resume point gets history back; a fresh
        # browser tab should not be flooded with the buffer.
        replay_history = since is not None or last_event_id is not None
        metrics.incr("alert_streams_opened")
        served = 0

        def events() -> Iterator[str]:
            nonlocal served
            subscriber, snapshot = broker.subscribe()
            cursor = resume
            started = time.monotonic()
            try:
                # Tell the browser how quickly to reconnect if we drop.
                yield "retry: 3000\n\n"
                if replay_history:
                    for seq, payload in snapshot:
                        if seq > cursor:
                            yield format_event(seq, payload)
                            cursor = seq
                            served += 1
                while True:
                    elapsed = time.monotonic() - started
                    if duration is not None and elapsed >= duration:
                        return
                    timeout = heartbeat
                    if duration is not None:
                        timeout = max(0.05, min(heartbeat, duration - elapsed))
                    try:
                        seq, payload = subscriber.get(timeout=timeout)
                    except queue.Empty:
                        yield ": ping\n\n"
                        continue
                    if seq <= cursor:
                        continue
                    yield format_event(seq, payload)
                    cursor = seq
                    served += 1
            finally:
                # Runs on disconnect too: never leak a subscriber queue.
                broker.unsubscribe(subscriber)
                metrics.incr("alert_stream_events", served)

        return StreamingResponse(
            events(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
                "Connection": "keep-alive",
            },
        )

    @app.post(
        "/transform",
        tags=["pipeline"],
        summary="Run the medallion DAG (bronze -> silver -> gold -> lake)",
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={
            503: {"description": "Bus or warehouse is not wired into this server"},
            500: {"description": "A DAG task failed; the response names the failing task"},
        },
    )
    def trigger_transform(
        incremental: bool = Query(default=True, description="Watermark-based incremental build"),
    ) -> Any:
        """Runs the Medallion transformation pipeline DAG and updates Lake."""
        if bus is None or warehouse is None:
            return service_unavailable("event bus or warehouse is not wired into this server")
        lineage = LineageEmitter(settings.data_dir / "lineage.jsonl")
        classifier = PIIClassifier(settings.pii_manifest_path)

        def ingest_bronze() -> None:
            lineage.start(
                "ingest_bronze",
                inputs=["bus.orders", "bus.clicks", "bus.payments"],
                outputs=["bronze.orders", "bronze.clicks", "bronze.payments"],
            )
            loaded = {}
            for topic in ("orders", "clicks", "payments"):
                consumer = bus.consumer(topic, "api-bronze-ingest", auto_offset_reset="earliest")
                records = []
                while True:
                    rec = consumer.poll(0.05)
                    if rec is None:
                        break
                    records.append(rec)
                    if len(records) >= 1000:
                        break
                if records:
                    warehouse.load_bronze_from_records(topic, records)
                    consumer.commit()
                loaded[topic] = len(records)
                consumer.close()
            lineage.complete("ingest_bronze", extra=loaded)

        def pii_scan() -> None:
            rows = warehouse.bronze_rows("orders", 200)
            for r in rows:
                r["_table"] = "bronze.orders"
            manifest = classifier.load()
            if not manifest:
                classifier.build_from_rows(rows)
                classifier.save()
                warehouse.save_manifest(classifier.load())
                return
            findings = classifier.detect_unregistered(rows)
            if findings:
                raise RuntimeError(f"unregistered PII columns: {findings}")

        def build_silver() -> None:
            lineage.start(
                "build_silver",
                inputs=["bronze.orders", "bronze.payments"],
                outputs=["silver.customers", "silver.orders", "silver.payments"],
            )
            if incremental:
                stats = warehouse.build_silver_incremental(pii_salt=settings.pii_salt)
                lineage.complete("build_silver", extra=stats)
            else:
                warehouse.build_silver(pii_salt=settings.pii_salt)
                lineage.complete("build_silver")

        def build_gold() -> None:
            lineage.start(
                "build_gold",
                inputs=["silver.customers", "silver.orders"],
                outputs=["gold.customer_360", "gold.order_facts"],
            )
            if incremental:
                stats = warehouse.build_gold_incremental()
                lineage.complete("build_gold", extra=stats)
            else:
                warehouse.build_gold()
                lineage.complete("build_gold")

        def quality_gate() -> None:
            report = DataQualityEngine(warehouse).run_all()
            if not report.all_passed:
                failed = [r.check_name for r in report.results if not r.passed]
                raise RuntimeError(f"data quality gate failed: {failed}")

        def export_lake() -> None:
            warehouse.export_lake(settings.lake_root)

        dag = DAG(
            dag_id="medallion-api",
            tasks=[
                DAGTask("ingest_bronze", ingest_bronze, depends_on=[]),
                DAGTask("pii_scan", pii_scan, depends_on=["ingest_bronze"]),
                DAGTask("build_silver", build_silver, depends_on=["pii_scan"]),
                DAGTask("build_gold", build_gold, depends_on=["build_silver"]),
                DAGTask("quality_gate", quality_gate, depends_on=["build_gold"]),
                DAGTask("export_lake", export_lake, depends_on=["quality_gate"]),
            ],
        )
        results = dag.run()
        metrics.flush()
        return {
            "status": "ok",
            "incremental": incremental,
            "tasks": {
                k: {"ok": v.ok, "duration_s": round(v.duration_s, 3)} for k, v in results.items()
            },
        }

    @app.post(
        "/quality-gate",
        tags=["pipeline"],
        summary="Run the data-quality gate and store its run history",
        dependencies=[Depends(require_token), Depends(rate_limit)],
        responses={503: {"description": "Warehouse is not wired into this server"}},
    )
    def trigger_quality_gate() -> Any:
        """Runs the Data Quality engine and stores run history."""
        if warehouse is None:
            return service_unavailable("warehouse is not wired into this server")
        report = DataQualityEngine(warehouse).run_all()
        return {
            "status": "ok",
            "run_id": report.run_id,
            "all_passed": report.all_passed,
            "results": [
                {"check_name": r.check_name, "passed": r.passed, "detail": r.detail}
                for r in report.results
            ],
        }

    @app.get("/health", tags=["meta"], summary="Liveness + process overview (legacy shape)")
    def health() -> dict[str, object]:
        """Kept for the existing dashboard/Render probe. Prefer
        ``/health/live`` for liveness and ``/health/ready`` for readiness."""
        return {
            "status": "ok",
            "version": __version__,
            "backend": effective_backend,
            "requested_backend": requested_backend,
            "degraded": degraded,
            "turso_connected": warehouse.turso is not None if warehouse else False,
            "suppressed": erasure.suppressed_customers(),
        }

    @app.get("/health/live", tags=["meta"], summary="Liveness probe", include_in_schema=False)
    def health_live() -> dict[str, str]:
        return {"status": "alive"}

    @app.get("/health/ready", tags=["meta"], summary="Readiness probe")
    def health_ready(response: JSONResponse) -> Any:
        """503 until the warehouse answers, so a load balancer stops sending
        traffic to a process whose database is gone."""
        checks: dict[str, str] = {"warehouse": "ok", "bus": "ok"}
        if warehouse is None:
            checks["warehouse"] = "not_configured"
        else:
            try:
                warehouse.scalar("SELECT 1", local_only=True)
            except Exception as e:  # pragma: no cover - only on a broken DB
                checks["warehouse"] = f"error: {e}"
        if bus is None:
            checks["bus"] = "not_configured"
        ready = not any(v.startswith("error") for v in checks.values())
        if not ready:
            response.status_code = 503
        return {"status": "ready" if ready else "not_ready", "checks": checks}

    @app.get("/metrics", tags=["ops"], summary="Metric snapshot as JSON")
    def metrics_endpoint() -> dict[str, object]:
        return metrics.snapshot()

    @app.get(
        "/metrics/prometheus",
        tags=["ops"],
        summary="Prometheus scrape target (text exposition format)",
        response_class=PlainTextResponse,
        responses={200: {"content": {"text/plain; version=0.0.4": {}}}},
    )
    def metrics_prometheus() -> str:
        """Prometheus scrape target — standard text exposition format."""
        return metrics.render_prometheus()

    def require_warehouse() -> Warehouse:
        """Return the warehouse or fail with 503 problem+json.

        Every warehouse-backed route is registered even when no warehouse is
        wired up: the endpoint then answers honestly instead of 404ing, so a
        client can tell "not deployed" from "wrong URL".
        """
        if warehouse is None:
            raise HTTPException(
                status_code=503,
                detail="warehouse is not configured (EUROSTREAM_DUCKDB_PATH / data dir missing)",
            )
        return warehouse

    @app.get("/governance/erasure-audit", tags=["governance"])
    def erasure_audit() -> list[dict[str, object]]:
        return require_warehouse().query(
            "SELECT * FROM governance.erasure_audit_log ORDER BY completed_at DESC LIMIT 50"
        )

    @app.get("/governance/erasure-audit/verify", tags=["governance"])
    def verify_erasure_audit(
        cross_check: bool = Query(
            default=True,
            description=(
                "Also compare the log against governance.erasure_audit_log in "
                "the warehouse, which catches a truncated or edited tail"
            ),
        ),
    ) -> dict[str, object]:
        """Verify the tamper-evident audit trail.

        Checks the hash chain over the JSONL log (modified records break their
        own hash; removed or reordered ones break the link after them) and, by
        default, that every attestation exists in both copies with the same
        contents.

        Always answers 200: a failed verification is a finding to act on, not
        a malformed request. Automation should read ``ok`` (or use
        ``eurostream verify-audit``, which exits non-zero).
        """
        expected: list[dict[str, object]] | None = None
        db_error: str | None = None
        if cross_check:
            try:
                expected = require_warehouse().query("SELECT * FROM governance.erasure_audit_log")
            except Exception as exc:  # noqa: BLE001 - report, do not hide
                db_error = f"warehouse audit table unavailable: {exc}"

        result = verify_audit_log(settings.audit_log_path, expected=expected)
        errors = list(result.errors)
        if db_error is not None:
            errors.append(db_error)
        payload = result.to_dict()
        payload["errors"] = errors
        payload["ok"] = not errors
        payload["chain"] = {
            "seq": erasure.audit_chain.seq,
            "tip": erasure.audit_chain.tip,
        }
        return payload

    @app.get("/gold/customer-360", tags=["warehouse"])
    def customer_360(
        limit: int = Query(default=100, ge=1, le=1000),
        search: str | None = Query(default=None, max_length=64),
    ) -> list[dict[str, object]]:
        wh = require_warehouse()
        if search:
            return wh.query(
                "SELECT * FROM gold.customer_360 WHERE customer_id LIKE ? "
                "ORDER BY customer_id LIMIT ?",
                (f"%{search}%", int(limit)),
            )
        return wh.query(
            "SELECT * FROM gold.customer_360 ORDER BY customer_id LIMIT ?",
            (int(limit),),
        )

    @app.get("/gold/fraud_summary", tags=["warehouse"])
    def fraud_summary() -> list[dict[str, object]]:
        return require_warehouse().query(
            "SELECT * FROM gold.fraud_summary ORDER BY last_alert DESC"
        )

    @app.get("/fraud_alerts", tags=["warehouse"])
    def fraud_alerts(limit: int = Query(default=50, ge=1, le=500)) -> list[dict[str, object]]:
        """Raw bronze fraud alerts. If the table has not been built yet this is a
        503, never a silent swap for a differently-shaped gold table."""
        wh = require_warehouse()
        try:
            return wh.query(
                "SELECT * FROM bronze.fraud_alerts ORDER BY alert_ts DESC LIMIT ?",
                (int(limit),),
            )
        except Exception as exc:  # noqa: BLE001 - table may simply not exist yet
            logger.warning("bronze.fraud_alerts unavailable: %s", exc)
            raise HTTPException(
                status_code=503,
                detail="bronze.fraud_alerts is unavailable — run `eurostream transform` first",
            ) from exc

    @app.get("/governance/data_quality_runs", tags=["governance"])
    def data_quality_runs(
        limit: int = Query(default=20, ge=1, le=200),
    ) -> list[dict[str, object]]:
        return require_warehouse().query(
            "SELECT * FROM governance.data_quality_runs ORDER BY checked_at DESC LIMIT ?",
            (int(limit),),
        )

    @app.get("/governance/suppression-registry", tags=["governance"])
    def suppression_registry() -> list[dict[str, object]]:
        return require_warehouse().query(
            "SELECT customer_id, added_at FROM governance.suppression_registry "
            "ORDER BY added_at DESC"
        )

    @app.get("/governance/watermarks", tags=["governance"])
    def watermarks_endpoint() -> list[dict[str, object]]:
        return require_warehouse().query("SELECT pipeline, last_ts FROM governance.watermarks")

    @app.post(
        "/sync-turso",
        tags=["warehouse"],
        dependencies=[Depends(require_token), Depends(rate_limit)],
        status_code=200,
    )
    def sync_turso_endpoint(
        seed_lake: bool = Query(default=True),
    ) -> dict[str, object]:
        """Sync local medallion state to the Turso cloud database.

        Reports per-table counts *and* per-table errors: a failed write is
        surfaced as a failed table, never as a fabricated zero.
        """
        wh = require_warehouse()
        if not wh.turso:
            raise HTTPException(
                status_code=503,
                detail="Turso not configured on server (TURSO_DATABASE_URL / TURSO_AUTH_TOKEN missing)",
            )
        if seed_lake:
            wh.seed_from_lake(settings.hf_repo)
        wh.sync_all_to_turso()

        table_counts: dict[str, int] = {}
        table_errors: dict[str, str] = {}
        assert wh.turso is not None  # noqa: S101 - guarded by the check above
        for tbl in Warehouse.TURSO_TABLES:
            try:
                table_counts[tbl] = int(wh.turso.scalar(f"SELECT count(*) FROM {tbl}"))
            except Exception as exc:  # noqa: BLE001 - report, do not fake success
                table_counts[tbl] = -1
                table_errors[tbl] = str(exc)
        status = "ok" if not table_errors else "partial"
        return {
            "status": status,
            "endpoint": wh.turso.http_endpoint,
            "seeded_lake": seed_lake,
            "table_counts": table_counts,
            "table_errors": table_errors,
        }

    @app.get("/turso/status", tags=["warehouse"])
    def turso_status_endpoint() -> dict[str, object]:
        """Turso connection status and per-table row counts (errors are reported)."""
        wh = require_warehouse()
        connected = wh.turso is not None
        table_counts: dict[str, int] = {}
        table_errors: dict[str, str] = {}
        if connected and wh.turso:
            for tbl in Warehouse.TURSO_TABLES:
                try:
                    table_counts[tbl] = int(wh.turso.scalar(f"SELECT count(*) FROM {tbl}"))
                except Exception as exc:  # noqa: BLE001
                    table_counts[tbl] = -1
                    table_errors[tbl] = str(exc)
        return {
            "connected": connected,
            "endpoint": wh.turso.http_endpoint if connected and wh.turso else None,
            # Breaker + retry telemetry: `state` is what the next write will
            # hit — open means it is being refused without a call.
            "circuit": wh.turso.status() if connected and wh.turso else None,
            "table_counts": table_counts,
            "table_errors": table_errors,
        }

    return app


def bootstrap() -> FastAPI:
    """Wire the API to the default runtime stack."""
    from eurostream.bus.sqlite import open_bus

    settings = Settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    bus: Any = None
    if settings.event_bus_backend == "kafka":
        try:
            from eurostream.bus.kafka import KafkaBus

            bus = KafkaBus(settings)
        except (ImportError, ModuleNotFoundError, ValueError) as e:
            logger.warning(
                "Kafka backend requested but unavailable (%s) — falling back to SQLite", e
            )
            bus = None
    if bus is None:
        bus = open_bus(settings.data_dir / "events.db")
    assert bus is not None
    warehouse = Warehouse(
        settings.warehouse_path,
        turso_url=settings.turso_database_url,
        turso_token=settings.turso_auth_token,
    )
    metrics = Metrics(settings.metrics_path)

    def refresh_lake(_audit: ErasureAudit) -> None:
        warehouse.export_lake(settings.lake_root)

    erasure = ErasureService(
        warehouse=warehouse,
        producer=bus,
        consumer=bus.consumer("erasure_requests", "api-worker", auto_offset_reset="earliest"),
        audit_log_path=settings.audit_log_path,
        metrics=metrics,
        sla_seconds=settings.erasure_sla_seconds,
        on_complete=refresh_lake,
    )
    return create_app(erasure, metrics, settings, warehouse, bus)


app = bootstrap()
